export const projects = [
  {
    title: 'Family-Driver',
    description: "“Family Driver” is based on “same driver, same client” concept that address many challenges ride-sharing service customers and companies face",
    image: '/images/1.jpg',
    tags: ['Wordpress', 'PHP'],
    source: 'https://www.family-driver.com/',
    visit: 'https://www.family-driver.com/',
    id: 0,
  },
  {
    title: 'CleanyCleaning',
    description: "A Team Of Professionals Dedicated To Making Your Life Easier And More Comfortable",
    image: '/images/2.png',
    tags: ['Wordpress', 'PHP'],
    source: 'https://www.cleanycleaning.com/',
    visit: 'https://www.cleanycleaning.com/',
    id: 1,
  },
  {
    title: 'E-Commerce',
    description: "Amazing home-made cookies online ordering",
    image: '/images/3.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://cookies-by-anna.netlify.app/',
    visit: 'https://cookies-by-anna.netlify.app/',
    id: 2,
  },
  {
    title: 'Chat-app',
    description: "Easy communicating with friends and family",
    image: '/images/4.png',
    tags: ['React', 'ChatEngine'],
    source: 'https://chat-app-eddiecale.netlify.app/',
    visit: 'https://chat-app-eddiecale.netlify.app/',
    id: 3,
  },
  {
    title: 'Video-Chat-app',
    description: "See each other and talk free",
    image: '/images/5.png',
    tags: ['React', 'Firebase'],
    source: 'https://ed-video-chat-app.netlify.app/',
    visit: 'https://ed-video-chat-app.netlify.app/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 1985, text: 'Worked as translator in the USSR chambers of commerce', },
  { year: 1990, text: 'Vice-President of the Soviet Association for cooperation with Japan', },
  { year: 1992, text: 'General Manager in Business Contact LLC', },
  { year: 1996, text: 'Executive Director in Business Plus LLC', },
  { year: 2015, text: 'CEO in Investment Brothers LLC', },
];